apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: monitoring
    prometheus.io/scrape: "true"
  labels:
    k8s-app: node-exporter-nfs-server
    jobLabel: node-exporter-nfs-server
  name: prom-node-exporter-nfs-server
  namespace: monitoring
spec:
  externalName: nfs-server
  ports:
    - port: 9100
      name: metrics
      protocol: TCP
      targetPort: 9100
  type: ExternalName