apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: node-exporter-nfs-server
  name: prom-node-exporter-nfs-server
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.1.110
        nodeName: nfsserver
    ports:
      - port: 9100
        name: metrics
        protocol: TCP